var bp_honor = {
	"fibosrockskr": ["Fibos Rocks 浏览器", "51Token 钱包", "dApp 开发者", "节点英雄", "遵守分红共识"],
	"fibos123comm": ["FIBOS 导航", "节点英雄", "遵守分红共识"],
	"ansenironman": ["IronMan 作者"],
	"ilovefibosbp": ["FOToolkit 作者"],
	"fibosisfunoo": ["dApp 开发者"],

	"slowmistioio": ["节点英雄"],
	"fibosgenesis": ["节点英雄"],
	"eosteaeostea": ["节点英雄"],

	"liuqiangdong": ["FIBOS 数据备份", "遵守分红共识"],
	"zhangsenyuan": ["dApp 开发者", "遵守分红共识"],
	"fibscandotio": ["FIBSCAN 浏览器", "遵守分红共识"],
	"lijialintest": ["遵守分红共识"],
	"superbpusphl": ["遵守分红共识"],
	"shaoshaoshao": ["遵守分红共识"],
	"williamfouvy": ["遵守分红共识"],
	"singaporebps": ["遵守分红共识"],
	"ukfiboooooos": ["遵守分红共识"],
	"fotothemooon": ["遵守分红共识"],
	"aprilfibosbp": ["遵守分红共识"],
	"bitzebitze11": ["遵守分红共识"],
	"beedappchina": ["dApp 活动赞助商"],
};